### ISSUE TITLE
Status do projeto

### ISSUE THREAD

**Issue by fernandoporazzi** [nTIFACCAT/CESEP#1]
Esse projeto aqui não vai ter continuidade?

**Comment by rafaelks** [comment]
@fernandoporazzi Terá, assim que encontrarmos alguém para tocar! Tens interesse? :-)

**Comment by fernandoporazzi** [comment]
Se arrumar mais uns 2 interessados, sim. Tenho medo de abraçar sozinho e não conseguir terminar =)

**Comment by danielrohers** [comment]
@rafaelks @fernandoporazzi +1 :)

**Comment by rafaelks** [comment]
@danielrohers @fernandoporazzi: Tenho certeza que vocês conseguem desenvolver sozinhos, caso ninguém mais queira. :+1: 

Se estiverem afim, converso com o pessoal do CESEP & FACCAT para tocarmos novamente.

**Comment by danielrohers** [comment]
@rafaelks também tenho certeza, a grande questão é tempo. Então, acredito que poderias conversar com eles ou passar a idéia do projeto melhor para ter uma idéia melhor do projeto/tempo.

**Comment by rafaelks** [comment]
@danielrohers Não é nada com **urgência**, somente precisa ser feito. Se estivermos tocando um projeto e vocês estiverem aprendendo ao mesmo tempo, está perfeito! :smile:

**Comment by danielrohers** [comment]
Por eu podemos tocar o projeto

**Comment by fernandoporazzi** [comment]
@rafaelks Assim que tu tiver alguma informação sobre a aplicação, entre em contato. Segue o baile!

**Comment by rafaelks** [comment]
@fernandoporazzi @danielrohers Ótimo, pode deixar!

**Comment by rafaelks** [comment]
@fernandoporazzi @danielrohers: Já conversei com eles, irão voltar a trabalhar em Fevereiro e retomamos a conversa lá. Vou atualizando vocês das novidades.

Valeu!

**Comment by fernandoporazzi** [comment]
Ficamos no aguardo então!
